In [10]:
class Employee:
    # Class variable to count the number of employees
    employee_count = 0
    
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        # Increment the employee count when a new employee is created
        Employee.employee_count += 1
    
    def average_salary(self, *salaries):
        total_salary = sum(salaries) + self.salary
        average = total_salary / (len(salaries) + 1)
        return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, hours_per_week):
        # Call the constructor of the parent class
        super().__init__(name, family, salary, department)
        self.hours_per_week = hours_per_week

# Creating instances of Employee and FulltimeEmployee classes
employee1 = Employee("anusree", "Family sree", 50000, "HR")
employee2 = FulltimeEmployee("vicky", "Family vicky", 60000, "IT", 40)

# Calling member functions
average_salary_employee1 = employee1.average_salary(70000, 60000)
print(f"Average Salary for Employee 1: ${average_salary_employee1}")

average_salary_employee2 = employee2.average_salary(65000, 70000)
print(f"Average Salary for Employee 2: ${average_salary_employee2}")

# Accessing class variable
print(f"Total Number of Employees: {Employee.employee_count}")

Average Salary for Employee 1: $60000.0
Average Salary for Employee 2: $65000.0
Total Number of Employees: 2


In [11]:
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 (along axis=1)
reshaped_array[np.arange(reshaped_array.shape[0]), np.argmax(reshaped_array, axis=1)] = 0

print("Original Random Vector:")
print(random_vector)
print("\nReshaped Array (4 by 5):")
print(reshaped_array)


Original Random Vector:
[ 0.          9.76117129  8.71862738  9.87043393  6.80135197 14.3717517
  3.4019444   1.66352768  0.          5.8425179  16.38431582 17.22128242
 14.19225463  0.         12.44585103 12.03512847  1.70506678 10.54115394
  0.         13.86386172]

Reshaped Array (4 by 5):
[[ 0.          9.76117129  8.71862738  9.87043393  6.80135197]
 [14.3717517   3.4019444   1.66352768  0.          5.8425179 ]
 [16.38431582 17.22128242 14.19225463  0.         12.44585103]
 [12.03512847  1.70506678 10.54115394  0.         13.86386172]]
